export const HIDE_FILTER_DETAIL_COMPONENT = 'HIDE_FILTER_DETAIL_COMPONENT';
export const SHOW_FILTER_DETAIL_COMPONENT = 'SHOW_FILTER_DETAIL_COMPONENT';
export const ADD_NEW_FILTER = 'ADD_NEW_FILTER'; // the button 'Add New Filter' is clicked
export const APPLY_FILTER = 'APPLY_FILTER'; // apply filter to the datatable without save it to the database
export const SAVE_NEW_FILTER = 'SAVE_NEW_FILTER';
export const SAVE_FILTER = 'SAVE_FILTER';
export const UPDATE_FILTER = 'UPDATE_FILTER';
export const DELETE_FILTER = 'DELETE_FILTER';
export const CHANGE_FILTER = 'CHANGE_FILTER';